name: ChatGuard

on:
  issues:
    types: [opened, edited]
  discussion:
    types: [created, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited]
  discussion_comment:
    types: [created, edited]

jobs:
  analyze_content:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze Comments with ChatGPT
        uses: your-organization/chat-guard@v0
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
